version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tare
      POSTGRES_PASSWORD: tare
      POSTGRES_DB: tare
    ports:
      - "5432:5432"
