[project]
name = "tare-workspace"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
  "python_modules/tare",
  "python_modules/tare-graphql",
  "python_modules/tare-webserver"
]
