[project]
name = "tare-graphql"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "strawberry-graphql[fastapi]",
    "uvicorn",
    "sqlalchemy",
    "pytest",
    "httpx",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
