[project]
name = "tare"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "typer",
]

[project.scripts]
tare = "tare.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
